# Generated by Django 4.0.5 on 2022-06-22 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midcategory',
            old_name='product',
            new_name='main_category',
        ),
        migrations.RenameField(
            model_name='producttag',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='product',
            new_name='mid_category',
        ),
        migrations.RemoveField(
            model_name='categoryproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='product',
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(related_name='sub_category', through='products.CategoryProduct', to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tag', through='products.ProductTag', to='products.tag'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
